### ISSUE TITLE
could not find function "FOCuS_offline"

### ISSUE THREAD

**Issue by raphael-fua** [gtromano/FOCuS#9] opened 2022-02-22 11:01 UTC
When running cost_function_illustration.R, I get the following error

Error in FOCuS_offline(y = y[1:(start + i)], mu0 = 0, thres = Inf) : 
  could not find function "FOCuS_offline"

**Comment by gtromano** [comment] 2022-02-22 16:47
Dear Raphael, 

this bug was caused by a previous interface (now deprecated) to FOCuS. Hopefully the issue should be fixed now.

**Closed** 2022-03-22 09:18 UTC
